# Generated by Django 3.2.6 on 2021-09-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=89)),
                ('age', models.PositiveIntegerField()),
                ('father_name', models.CharField(max_length=89)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('nid_number', models.IntegerField()),
                ('occupassion', models.CharField(max_length=89)),
                ('illness', models.CharField(max_length=89)),
                ('religion', models.CharField(max_length=55)),
                ('child_count', models.IntegerField()),
                ('living', models.CharField(max_length=144)),
                ('mobile_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='old/')),
            ],
        ),
    ]
