# Generated by Django 3.2.6 on 2021-09-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_place',
            field=models.CharField(blank=True, max_length=89, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(max_length=89),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_number',
            field=models.CharField(max_length=89),
        ),
        migrations.AlterField(
            model_name='person',
            name='nid_number',
            field=models.CharField(max_length=89),
        ),
    ]
