# Generated by Django 3.2.6 on 2021-09-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210907_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='child_count',
            field=models.CharField(max_length=89),
        ),
    ]
