# Generated by Django 3.2.6 on 2021-11-30 06:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_person_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='form_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='house_number',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='child_count',
            field=models.CharField(blank=True, max_length=89, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(blank=True, max_length=89, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='illness',
            field=models.CharField(blank=True, max_length=89, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[640, 480], upload_to='old/resized/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='living',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupassion',
            field=models.CharField(blank=True, max_length=89, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='religion',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
